In [2]:
import numpy as np

In [3]:
np.arange(0,20,4)

array([ 0,  4,  8, 12, 16])

In [4]:
#equal pieces
np.linspace(0,20,4)

array([ 0.        ,  6.66666667, 13.33333333, 20.        ])

In [5]:
np.random.seed(101) #to get the same result everytime
np.random.rand(3)


array([0.51639863, 0.57066759, 0.02847423])

In [6]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [7]:
np.ones(3)

array([1., 1., 1.])

In [9]:
arr=np.arange(1,100,7)

In [10]:
arr.shape

(15,)

In [11]:
arr

array([ 1,  8, 15, 22, 29, 36, 43, 50, 57, 64, 71, 78, 85, 92, 99])

In [12]:
arr.reshape(1,15).shape

(1, 15)

In [13]:
arr

array([ 1,  8, 15, 22, 29, 36, 43, 50, 57, 64, 71, 78, 85, 92, 99])

In [14]:
np.random.seed(101)
ranarr=np.random.randint(0,50,10)

In [15]:
ranarr

array([31, 11, 17,  6, 23, 11, 47,  9, 13, 40])

In [16]:
ranarr.max()

47

In [18]:
ranarr.min()

6

In [19]:
ranarr.argmax()  #return the index of max element along a given axis

6

In [20]:
ranarr.argmin()  #return the index of the minimum element along a given axis

3

In [22]:
np.linspace(0,40,5)

array([ 0., 10., 20., 30., 40.])

In [26]:
np.random.seed(42)
a=np.random.randint(10,size=10)
a

array([6, 3, 7, 4, 6, 9, 2, 6, 7, 4])

In [28]:
a.ndim #rows and columns=2 dimensions

1

In [30]:
b=np.random.randint(10,size=(3,5))
b

array([[0, 9, 2, 6, 3],
       [8, 2, 4, 2, 6],
       [4, 8, 6, 1, 3]])

In [31]:
b.shape

(3, 5)

In [32]:
b.size

15

In [33]:
b.ndim

2

In [34]:
b.dtype

dtype('int32')

In [35]:
b.itemsize #.itemsize: the size in bytes of each element of the array. 
#It is equivalent to  .dtype.itemsize.

4

In [38]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [39]:
x

array([1, 2, 3])

In [40]:
y

array([4, 5, 6])

In [41]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [42]:
x=np.array([1,2,3,99,99,3,2,1])
x

array([ 1,  2,  3, 99, 99,  3,  2,  1])

In [46]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [47]:
v=np.array([2,1,4,3,5])
v

array([2, 1, 4, 3, 5])

In [48]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [49]:
v.sort()

In [50]:
v.sum()

15

In [51]:
np.random.seed(42)
arr1=np.random.randint(1,9,9).reshape(3,3)
arr2=np.random.randint(1,9,9).reshape(3,3)
arr1

array([[7, 4, 5],
       [7, 3, 8],
       [5, 5, 7]])

In [52]:
arr2

array([[2, 3, 7],
       [3, 3, 8],
       [5, 4, 8]])

In [54]:
arr1+arr2

array([[ 9,  7, 12],
       [10,  6, 16],
       [10,  9, 15]])

In [55]:
arr1-arr2

array([[ 5,  1, -2],
       [ 4,  0,  0],
       [ 0,  1, -1]])

In [56]:
arr1/arr2

array([[3.5       , 1.33333333, 0.71428571],
       [2.33333333, 1.        , 1.        ],
       [1.        , 1.25      , 0.875     ]])

In [57]:
arr1*arr2

array([[14, 12, 35],
       [21,  9, 64],
       [25, 20, 56]])

In [58]:
np.sqrt(arr1)

array([[2.64575131, 2.        , 2.23606798],
       [2.64575131, 1.73205081, 2.82842712],
       [2.23606798, 2.23606798, 2.64575131]])

In [59]:
np.exp(arr2)  #return an array with exponential of all elements of input array

array([[   7.3890561 ,   20.08553692, 1096.63315843],
       [  20.08553692,   20.08553692, 2980.95798704],
       [ 148.4131591 ,   54.59815003, 2980.95798704]])

In [63]:
arr1.max(axis=1)  #return the maximum along a given axis

array([7, 8, 7])

In [64]:
arr1.max(axis=0)

array([7, 5, 8])

In [65]:
arr1.min(axis=1)

array([4, 3, 5])

In [66]:
arr1.mean(axis=0)

array([6.33333333, 4.        , 6.66666667])

In [68]:
np.median(arr1,axis=0)

array([7., 4., 7.])

In [69]:
arr1.sum(axis=0)

array([19, 12, 20])

In [71]:
from scipy import stats

In [73]:
stats.mode(arr1,axis=0)[0]

array([[7, 3, 5]])

In [74]:
np.sin(arr1)

array([[ 0.6569866 , -0.7568025 , -0.95892427],
       [ 0.6569866 ,  0.14112001,  0.98935825],
       [-0.95892427, -0.95892427,  0.6569866 ]])

In [75]:
arr=np.arange(1,37)
arr.shape

(36,)